rebellions-sw/optimum-rbln

- README.md
Since we don't have to use cuda-pytorch, users have another option for installation.
----
```
```
----
- Enhancements
- Other
> doc: Add CPU-torch Instruction

- README.md
----
```
```
----
- Enhancements
- Other
> doc: Remove Licence badge

- .github/scripts/auto_code_review.py
- examples/image-to-text/run_llava_next_image_to_text.py
- src/optimum/rbln/transformers/utils/rbln_quantization.py
- src/optimum/rbln/utils/logging.py
몇몇 코드에 ruff format이 누락되어있던 것을 적용합니다.
----
```
```
----
- Enhancements
- Other
> other: Apply ruff formatting

- src/optimum/rbln/utils/import_utils.py
Fixes https://github.com/rebellions-sw/optimum-rbln/issues/6
----
```
```
----
- Enhancements
- Other
> other: version warning false alarm

- pyproject.toml
- uv.lock
This PR removes einops, halo dependencies.
Also updates maximum torch version as the latest torch version is updated.
----
```
```
----
- Enhancements
- Other
> other: remove unnecessary dependencies

- src/optimum/rbln/transformers/models/llava_next/modeling_llava_next.py
legacy processing을 타야할 때 안 타는 문제.. 였던 것 같습니다 (정확히 파악된 건 아닙니다)
vllm 쪽에도 문제가 없을지 체크가 필요합니다. 
----
```
```
----
- Enhancements
- Other
> model: Llava bugfix when large image

- src/optimum/rbln/transformers/models/decoderonly/modeling_decoderonly.py
- src/optimum/rbln/transformers/utils/rbln_quantization.py
특정 환경에서 qLLM compile이 느린 경우가 있어, 문제 트래킹을 위한 로그
----
```
```
----
- Enhancements
- Other
> model: Add qLLM debugging log

- src/optimum/rbln/transformers/modeling_generic.py
- src/optimum/rbln/transformers/models/bart/modeling_bart.py
- src/optimum/rbln/transformers/models/bert/modeling_bert.py
- src/optimum/rbln/transformers/models/t5/modeling_t5.py
- src/optimum/rbln/transformers/models/xlm_roberta/modeling_xlm_roberta.py
make compile model input order with original hf model class forward()
----
```
```
----
- Enhancements
- Other
> model: fix rbln_model_input_names order

- src/optimum/rbln/ops/attn.py
- src/optimum/rbln/ops/flash_attn.py
- src/optimum/rbln/transformers/models/decoderonly/decoderonly_architecture.py
Update model to call multi-batch attention kernel to simplify model and clear attention kernel writing.
`rebel_compiler` update required
> model: call multi-batch attention kernel

- pyproject.toml
- src/optimum/rbln/transformers/models/decoderonly/decoderonly_architecture.py
- src/optimum/rbln/transformers/models/t5/t5_architecture.py
- tests/test_llm.py
- uv.lock
----
```
```
----
- Enhancements
- Other
> other: sync-up to the latest transformers(v4.48.3)

- src/optimum/rbln/modeling_base.py
save_pretrained를 할 때 shutil.copy를 쓰고 있어 기존 파일이 폴더에 남아있는 경우가 있음.
대신 temp dir에 copy한 다음, rename하는 식으로 변경합니다. 
아래는 챗봇 리뷰입니다. 
두 방식의 시나리오별 속도 비교를 해보겠습니다:
1. **save_directory가 존재하지 않는 경우**
```
기존 방식: 
- os.makedirs() -> copytree() -> save_config() 순차 실행
새로운 방식:
- rmtree(tmp) -> copytree() -> save_config() -> rename() 순차 실행
➡️ 새 방식이 약간 더 느림 (임시 디렉토리 제거 + rename 작업 추가)
```
2. **save_directory가 이미 존재하는 경우**
```
기존 방식:
- copytree(dirs_exist_ok=True): 파일별로 존재 여부 확인하고 덮어쓰기
새로운 방식: 
- copytree(tmp) -> rmtree(target) -> rename(tmp, target)
➡️ 대부분의 경우 새 방식이 더 빠름
- 기존 방식은 모든 파일에 대해 존재 여부 체크 필요
- 새 방식은 파일 단위가 아닌 디렉토리 단위 연산
```
3. **저장 중 오류가 발생하는 경우**
```
기존 방식:
- 파일별 복사 중 실패 시 일부 파일만 복사된 상태로 중단
- 기존 파일과 새 파일이 섞인 상태가 됨
새로운 방식:
- 임시 디렉토리에 복사 중 실패해도 원본 디렉토리는 안전
- cleanup만 필요
➡️ 새 방식이 안전성 높음, 복구 비용 낮음
```
4. …
> other: modify save logic

- src/optimum/rbln/diffusers/models/autoencoders/autoencoder_kl.py
- src/optimum/rbln/diffusers/models/autoencoders/vae.py
- src/optimum/rbln/diffusers/models/controlnet.py
- src/optimum/rbln/diffusers/models/transformers/transformer_sd3.py
- src/optimum/rbln/diffusers/models/unets/unet_2d_condition.py
- src/optimum/rbln/diffusers/pipelines/controlnet/multicontrolnet.py
- src/optimum/rbln/diffusers/pipelines/controlnet/pipeline_controlnet.py
- src/optimum/rbln/modeling.py
- src/optimum/rbln/modeling_base.py
- src/optimum/rbln/transformers/models/bert/modeling_bert.py
- src/optimum/rbln/transformers/models/clip/modeling_clip.py
- src/optimum/rbln/transformers/models/dpt/modeling_dpt.py
- src/optimum/rbln/transformers/models/llava_next/modeling_llava_next.py
- src/optimum/rbln/transformers/models/seq2seq/modeling_seq2seq.py
- src/optimum/rbln/transformers/models/wav2vec2/modeling_wav2vec2.py
- src/optimum/rbln/transformers/models/whisper/modeling_whisper.py
- src/optimum/rbln/transformers/models/xlm_roberta/modeling_xlm_roberta.py
- src/optimum/rbln/utils/save_utils.py
Replace built-in loggers with optimum rbln loggers
https://github.com/rebellions-sw/optimum-rbln/pull/15#discussion_r1948369186
----
```
```
----
- Enhancements
- Other
> refactor: replace built-in loggers into optimum rbln loggers

- src/optimum/rbln/diffusers/modeling_diffusers.py
- src/optimum/rbln/modeling.py
- src/optimum/rbln/modeling_base.py
- src/optimum/rbln/transformers/modeling_generic.py
- src/optimum/rbln/transformers/models/bart/modeling_bart.py
- src/optimum/rbln/transformers/models/bert/modeling_bert.py
- src/optimum/rbln/transformers/models/decoderonly/modeling_decoderonly.py
- src/optimum/rbln/transformers/models/t5/modeling_t5.py
- src/optimum/rbln/transformers/models/xlm_roberta/modeling_xlm_roberta.py
- tests/test_base.py
- tests/test_llm.py
- tests/test_transformers.py
https://docs.python.org/3.13/whatsnew/3.13.html#builtins
class property가 python 3.11부터 deprecate되었으며 python 3.13부터는 지원되지 않습니다. 
----
```
```
----
- Enhancements
- Other
> refactor: no class property

- src/optimum/rbln/transformers/models/decoderonly/modeling_decoderonly.py
----
```
```
----
- Enhancements
- Other
> other: paged_attn's internal blocktables for generate

- .github/scripts/auto_code_review.py
- .github/workflows/auto_code_review.yml
----
```
```
----
- Enhancements
- Other
> other(autoreview): based on commit message, issue message

- src/optimum/rbln/transformers/models/decoderonly/modeling_decoderonly.py
----
```
```
----
- Enhancements
- Other
> other: improve block_table management

- .github/version.yaml
- src/optimum/rbln/transformers/models/decoderonly/modeling_decoderonly.py
- src/optimum/rbln/transformers/models/phi/phi_architecture.py
----
```
```
----
- Enhancements
- Other
> other: rebel-compiler version update

- src/optimum/rbln/modeling_base.py
- src/optimum/rbln/transformers/models/decoderonly/modeling_decoderonly.py
필요없는 check compiled models 를 지우고
불필요하게 함수화되어있던 kernel size / block nbytes estimation 로직을 풀었습니다
----
```
```
----
- Enhancements
- Other
> refactor(llm): cleanup paged attention estimation

- src/optimum/rbln/transformers/models/decoderonly/modeling_decoderonly.py
----
```
```
----
- Enhancements
- Other
> refactor: minor fix for no block error msg

- src/optimum/rbln/transformers/models/bart/modeling_bart.py
- src/optimum/rbln/transformers/models/seq2seq/modeling_seq2seq.py
- src/optimum/rbln/transformers/models/t5/modeling_t5.py
----
```
```
----
- Enhancements
- Other
> refactor(seq2seq): adapt to paged_attn and causal_attn

- src/optimum/rbln/diffusers/modeling_diffusers.py
- src/optimum/rbln/diffusers/pipelines/kandinsky2_2/pipeline_kandinsky2_2_combined.py
- tests/test_diffusers.py
Support a connected pipeline using existing methods
- implement `_compile_pipelines` to compile submodules within a connected pipeline structure
- remove newly added implementations that support a connected pipeline structure
- reuse existing implementations for supporting a single pipeline structure
- implement config preparation methods 
- `_prepare_rbln_config`: prepare an RBLN config for a connected pipeline structure (suitable for compile submodules)
- `_flatten_rbln_config`: flatten an RBLN config like a single pipeline structure (suitable for load submodules)
- set the class variable `_submodules` of a combined pipeline as a list of submodules, not that of connected pipelines
----
```
```
----
- `model`: Adding New models or Bugfix …
> refactor: resolve connected pipe

- .github/version.yaml
- src/optimum/rbln/utils/import_utils.py
----
```
```
----
- Enhancements
- Other
> dependency: 0.7.3

- src/optimum/rbln/transformers/models/bart/modeling_bart.py
- src/optimum/rbln/transformers/models/seq2seq/modeling_seq2seq.py
- src/optimum/rbln/transformers/models/t5/modeling_t5.py
----
```
```
----
- Enhancements
- Other
> other: Revert #64, #65

- .github/version.yaml
- src/optimum/rbln/ops/__init__.py
- src/optimum/rbln/ops/attn.py
- src/optimum/rbln/transformers/models/bart/modeling_bart.py
- src/optimum/rbln/transformers/models/seq2seq/modeling_seq2seq.py
- src/optimum/rbln/transformers/models/t5/modeling_t5.py
- src/optimum/rbln/transformers/models/t5/t5_architecture.py
- src/optimum/rbln/transformers/models/whisper/modeling_whisper.py
- src/optimum/rbln/transformers/models/whisper/whisper_architecture.py
----
```
```
----
- Enhancements
- Other
> model(t5): paged add softmax attn decode

- src/optimum/rbln/transformers/models/bart/modeling_bart.py
- tests/test_transformers.py
connection 연결 bug 제거하는 pr입니다.
----
```
```
----
- Enhancements
- Other
> model: BartModel bugfix

- pyproject.toml
- src/optimum/rbln/transformers/models/seq2seq/modeling_seq2seq.py
- src/optimum/rbln/transformers/models/whisper/modeling_whisper.py
- src/optimum/rbln/transformers/models/whisper/whisper_architecture.py
- tests/test_transformers.py
- uv.lock
최종 완성은 vllm code까지 작업한 후에 같이 merge 하겠습니다.
----
```
```
----
- Enhancements
- Other
> model: whisper cb & paged attn & causal

- .github/workflows/auto_code_review.yml
- .github/workflows/check_code_quality.yml
- .github/workflows/pr-title-check.yaml
- .github/workflows/pr_checklist_validator.yml
----
```
```
----
- Enhancements
- Other
> other(ci): update action runner

- src/optimum/rbln/transformers/models/whisper/whisper_architecture.py
remove whipser model device context to 1
----
```
```
----
- Enhancements
- Other
> model: whisper models device context bugfix

- src/optimum/rbln/transformers/models/t5/modeling_t5.py
----
```
```
----
- Enhancements
- Other
> model: fix T5EncoderModel for embedding model

- .github/workflows/rbln_optimum_pytest.yaml
Schedule run fails when the latest commit message contains multi-lines
----
```
```
----
- Enhancements
- Other
> other(ci): fix commit message parsing

- src/optimum/rbln/transformers/models/t5/modeling_t5.py
Reverts rebellions-sw/optimum-rbln#81, 
It will be restored after https://github.com/rebellions-sw/optimum-rbln/pull/67
----
```
```
----
- Enhancements
- Other
> model: Revert "model: fix T5EncoderModel for embedding model"

- .github/workflows/deploy-on-tag.yaml
> other: fix input type in request other repo dispatch CI when tagging

- examples/question-answering/run_question_answering.py
- tests/test_base.py
It looks like there is some code left over for the old rbln_config, fix it.
----
```
```
----
- Enhancements
- Other
> other: fix deprecated code for legacy rbln_config

- .github/ISSUE_TEMPLATE/model_request.md
- .github/scripts/auto_code_review.py
- pyproject.toml
- src/optimum/rbln/diffusers/modeling_diffusers.py
- src/optimum/rbln/modeling_base.py
- src/optimum/rbln/transformers/models/auto/auto_factory.py
- src/optimum/rbln/utils/hub.py
- src/optimum/rbln/utils/model_utils.py
1. `Hugging Face` -> `HuggingFace`
2. remove img2img_pipeline
3. fix type hint for DiffuserMixin
----
```
```
----
- Enhancements
- Other
> model(diffusers): Simple fix for docstirng

- src/optimum/rbln/__init__.py
- src/optimum/rbln/diffusers/__init__.py
- src/optimum/rbln/diffusers/configurations/__init__.py
- src/optimum/rbln/diffusers/configurations/models/__init__.py
- src/optimum/rbln/diffusers/configurations/models/configuration_autoencoder_kl_cosmos.py
- src/optimum/rbln/diffusers/models/autoencoders/autoencoder_kl_cosmos.py
- src/optimum/rbln/diffusers/models/transformers/transformer_cosmos.py
- src/optimum/rbln/diffusers/pipelines/cosmos/cosmos_guardrail.py
RBLNConfig for Cosmos Guardrail models
----
```
```
----
- Enhancements
- Other
> model: add RBLNConfig for cosmos guardrail

- src/optimum/rbln/configuration_utils.py
- src/optimum/rbln/modeling_base.py
- tests/test_base.py
- tests/test_llm.py
when export=False, passing submodule's config raises error.
This pr fixes it.
----
```
```
----
- Enhancements
- Other
> model(base): Fix submodule load

- src/optimum/rbln/diffusers/modeling_diffusers.py
- src/optimum/rbln/diffusers/pipelines/controlnet/pipeline_controlnet.py
- src/optimum/rbln/diffusers/pipelines/controlnet/pipeline_controlnet_img2img.py
- src/optimum/rbln/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py
- src/optimum/rbln/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl_img2img.py
- src/optimum/rbln/diffusers/pipelines/kandinsky2_2/pipeline_kandinsky2_2.py
- src/optimum/rbln/diffusers/pipelines/kandinsky2_2/pipeline_kandinsky2_2_combined.py
- src/optimum/rbln/diffusers/pipelines/kandinsky2_2/pipeline_kandinsky2_2_img2img.py
- src/optimum/rbln/diffusers/pipelines/kandinsky2_2/pipeline_kandinsky2_2_inpaint.py
- src/optimum/rbln/diffusers/pipelines/kandinsky2_2/pipeline_kandinsky2_2_prior.py
- src/optimum/rbln/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- src/optimum/rbln/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py
- src/optimum/rbln/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py
- src/optimum/rbln/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3.py
- src/optimum/rbln/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3_img2img.py
- src/optimum/rbln/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3_inpaint.py
- src/optimum/rbln/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py
- src/optimum/rbln/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py
- src/optimum/rbln/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py
Added config class as a class member.
Users can browse pipeline's configuration easily if they use IDE.
----
```
```
----
- Enhancements
- Other
> model(diffusers): Add config for every pipelines

- src/optimum/rbln/diffusers/configurations/models/configuration_autoencoder_kl_cosmos.py
- src/optimum/rbln/diffusers/configurations/pipelines/configuration_cosmos.py
Decoder config update
----
```
```
----
- Enhancements
- Other
> model: Bugfix cosmos decoder

- src/optimum/rbln/diffusers/models/controlnet.py
- src/optimum/rbln/diffusers/models/transformers/transformer_sd3.py
- src/optimum/rbln/diffusers/models/unets/unet_2d_condition.py
Update links as document update.
This PR should be merged after the update of document
----
```
```
----
- Enhancements
- Other
> doc: update links as document page update

- .github/version.yaml
- tests/test_llm.py
As title describes
----
```
```
----
- Enhancements
- Other
> other: Update ci compiler version

- src/optimum/rbln/__init__.py
- tests/test_base.py
Now users can access library's version via `optimum.rbln.__version__`
----
```
```
----
- Enhancements
- Other
> other: Reachable version obj

- src/optimum/rbln/transformers/models/decoderonly/modeling_decoderonly.py
----
```
```
----
- Enhancements
- Other
> model(decoderonly): bugfix access NoneType attention_mask at decode_forward

- src/optimum/rbln/configuration_utils.py
- src/optimum/rbln/transformers/models/decoderonly/configuration_decoderonly.py
- src/optimum/rbln/transformers/models/decoderonly/modeling_decoderonly.py
- src/optimum/rbln/transformers/utils/rbln_quantization.py
We're refactoring to a quantization config that is more flexible and interpretable at the code level, as we plan to support different quantization schemes in the future.
Additionally, we improved the functionality of the function to load weights from local directory only, so that it can also load from huggingface hub.
----
```
```
----
- Enhancements
- …
> other(llm): refactor quantization config

- src/optimum/rbln/diffusers/configurations/pipelines/configuration_controlnet.py
- src/optimum/rbln/diffusers/configurations/pipelines/configuration_kandinsky2_2.py
- src/optimum/rbln/diffusers/configurations/pipelines/configuration_stable_diffusion.py
- src/optimum/rbln/diffusers/configurations/pipelines/configuration_stable_diffusion_3.py
- src/optimum/rbln/diffusers/configurations/pipelines/configuration_stable_diffusion_xl.py
- src/optimum/rbln/modeling.py
----
```
```
----
- Enhancements
- Other
> refactor: Change configuration to support the same arguments as in HF

- src/optimum/rbln/transformers/models/gemma3/modeling_gemma3.py
----
```
```
----
- Enhancements
- Other
> Model: Gemma3 eager attention, not supported yet

- src/optimum/rbln/transformers/models/gemma3/modeling_gemma3.py
This reverts commit 5e014a33f096604c63fd2ec85f52f4ef52f228c7.
----
```
```
----
- Enhancements
- Other
> Revert "Model: Gemma3 eager attention, not supported yet (#148)"

- src/optimum/rbln/transformers/models/qwen2_5_vl/modeling_qwen2_5_vl.py
----
```
```
----
- Enhancements
- Other
> Fix: remove debugging code

- src/optimum/rbln/transformers/models/qwen2_5_vl/modeling_qwen2_5_vl.py
----
```
```
----
- Enhancements
- Other
> other: minor cleaning of qwen2_5_vl

- src/optimum/rbln/diffusers/pipelines/kandinsky2_2/pipeline_kandinsky2_2_combined.py
Without this change, kandinsky raises an error when diffusers >= 0.33
----
```
```
----
- Enhancements
- Other
> model(kandinsky): fix type annotation for kandinsky

- src/optimum/rbln/modeling.py
----
```
```
----
- Enhancements
- Other
> doc: Update docstring only in `from_model` method

- src/optimum/rbln/transformers/models/decoderonly/modeling_decoderonly.py
- src/optimum/rbln/transformers/models/gemma3/modeling_gemma3.py
----
```
```
----
- Enhancements
- Other
> model: gemma3 hot fix

- src/optimum/rbln/transformers/models/clip/modeling_clip.py
- src/optimum/rbln/transformers/models/siglip/modeling_siglip.py
----
```
```
----
- Enhancements
- Other
> model: SiglipVisionModel output bug

- src/optimum/rbln/configuration_utils.py
- tests/test_config.py
npu and tp size were not passed to submodules of diffusers pipeline config.
This PR fixes it.
----
```
```
----
- Enhancements
- Other
> model(diffusers): fix configuration inherit

- src/optimum/rbln/transformers/models/siglip/modeling_siglip.py
fix docstring of SiglipVisionModel forward function properly
----
```
```
----
- Enhancements
- Other
> model(SiglipVisionModel): forward docstring only

- src/optimum/rbln/transformers/models/siglip/configuration_siglip.py
- src/optimum/rbln/transformers/models/siglip/modeling_siglip.py
fix default value of forward argument
----
```
```
----
- Enhancements
- Other
> model(SiglipVisionModel): default value of forward arguments

- src/optimum/rbln/transformers/models/qwen2_5_vl/qwen2_5_vl_architecture.py
----
```
```
----
- Enhancements
- Other
> model: Qwen2.5-VL bug fix after #162

- src/optimum/rbln/transformers/models/siglip/modeling_siglip.py
fix output order of siglip forward function
----
```
```
----
- Enhancements
- Other
> model(Siglip): fix output order properly

- src/optimum/rbln/transformers/models/decoderonly/modeling_decoderonly.py
- src/optimum/rbln/transformers/models/gemma3/modeling_gemma3.py
- tests/test_llm.py
----
```
```
----
- Enhancements
- Other
> model: fix bug of decoderonly runtime

- src/optimum/rbln/diffusers/models/controlnet.py
Because importing `ControlNetOutput` from `diffusers.models.controlnet` is deprecated after `diffusers==0.34.0`, it is changed like below.
```diff
import torch
from diffusers import ControlNetModel
-from diffusers.models.controlnet import ControlNetOutput
+from diffusers.models.controlnets.controlnet import ControlNetOutput
from transformers import PretrainedConfig
```
FYI, https://github.com/huggingface/diffusers/blob/88466358733da21a4ab45d85300ee6960f588e7d/src/diffusers/models/controlnet.py#L25-L29
----
```
```
----
- Enhancements
- ex) …
> refactor: update import ControlNetOutput

- pyproject.toml
- uv.lock
----
```
```
----
- Enhancements
- Other
> dependency: fix torch version

- src/optimum/rbln/diffusers/models/autoencoders/autoencoder_kl_cosmos.py
Resolve errors while supporting cosmos pipelines
----
```
```
----
- Enhancements
- Other
> other: resolve error while compiling cosmos v2w decoder

- src/optimum/rbln/diffusers/models/autoencoders/autoencoder_kl.py
- src/optimum/rbln/diffusers/models/autoencoders/autoencoder_kl_cosmos.py
- src/optimum/rbln/diffusers/models/autoencoders/vq_model.py
- src/optimum/rbln/modeling.py
- src/optimum/rbln/modeling_base.py
- src/optimum/rbln/transformers/models/decoderonly/modeling_decoderonly.py
- src/optimum/rbln/transformers/models/gemma3/modeling_gemma3.py
- src/optimum/rbln/transformers/models/seq2seq/modeling_seq2seq.py
- src/optimum/rbln/transformers/models/time_series_transformer/modeling_time_series_transformer.py
- src/optimum/rbln/transformers/models/whisper/modeling_whisper.py
- src/optimum/rbln/utils/runtime_utils.py
- tests/test_config.py
- tests/test_transformers.py
If the compile function is passed compile settings that prevent it from generating runtimes on this machine, and create_runtimes=True, cause it to raise an error before compiling.
----
```
```
----
- Enhancements
- Other
- ex) pdm …
> other: pre-check compile config

- src/optimum/rbln/diffusers/pipelines/cosmos/pipeline_cosmos_video2world.py
fix `_optional_components` to `_optional_submodules`
----
```
```
----
- Enhancements
- Other
> model: bugfix cosmos v2w

- src/optimum/rbln/diffusers/configurations/models/configuration_autoencoder_kl_cosmos.py
- src/optimum/rbln/diffusers/configurations/models/configuration_transformer_cosmos.py
- src/optimum/rbln/diffusers/configurations/pipelines/configuration_cosmos.py
- src/optimum/rbln/transformers/models/blip_2/configuration_blip_2.py
- src/optimum/rbln/transformers/models/colpali/configuration_colpali.py
----
```
```
----
- Enhancements
- Other
> doc: sync docstring only

- src/optimum/rbln/transformers/models/decoderonly/decoderonly_architecture.py
remaining issue for colqwen -> custom class
- add _use_learned_pos_emb flag for wrapper
----
```
```
----
- Enhancements
- Other
> model(llm): fix refactor architecture attention ops

- src/optimum/rbln/configuration_utils.py
- src/optimum/rbln/diffusers/configurations/models/configuration_transformer_cosmos.py
- src/optimum/rbln/diffusers/modeling_diffusers.py
- src/optimum/rbln/diffusers/models/autoencoders/autoencoder_kl.py
- src/optimum/rbln/diffusers/models/autoencoders/autoencoder_kl_cosmos.py
- src/optimum/rbln/diffusers/models/autoencoders/vq_model.py
- src/optimum/rbln/diffusers/models/transformers/transformer_cosmos.py
- src/optimum/rbln/modeling.py
- src/optimum/rbln/transformers/models/decoderonly/modeling_decoderonly.py
- src/optimum/rbln/transformers/models/gemma3/modeling_gemma3.py
- src/optimum/rbln/transformers/models/seq2seq/modeling_seq2seq.py
- src/optimum/rbln/transformers/models/time_series_transformer/modeling_time_series_transformer.py
- src/optimum/rbln/transformers/models/whisper/modeling_whisper.py
- src/optimum/rbln/utils/runtime_utils.py
Add a new argument to `rbln_runtime_kwargs`.
Large models such as Cosmos transformer need longer runtime timeout, but runtime timeout cannot be set.
----
```
```
----
- Enhancements
- Other
> other: support runtime timeout

- src/optimum/rbln/transformers/models/bart/bart_architecture.py
Remove unnecessary code in `BartForConditionalGeneration`
----
```
```
----
- Enhancements
- Other
> refactor: simplify BartForConditionalGeneration code

- src/optimum/rbln/transformers/models/decoderonly/decoderonly_architecture.py
The condition that passes the attn_mask from EagerAttention to custom_op was buggy during the refactoring process, and I've found it now.
----
```
```
----
- Enhancements
- Other
> model: gemma3 bug fix with EagerAttention

- src/optimum/rbln/transformers/models/llava/modeling_llava.py
----
```
```
----
- Enhancements
- Other
> refactor: llava & pixtral  modeling

- .github/version.yaml
- src/optimum/rbln/transformers/models/decoderonly/decoderonly_architecture.py
- src/optimum/rbln/transformers/models/decoderonly/modeling_decoderonly.py
- src/optimum/rbln/transformers/models/gemma3/configuration_gemma3.py
- src/optimum/rbln/transformers/models/gemma3/modeling_gemma3.py
- tests/test_base.py
- tests/test_llm.py
----
```
```
----
- Enhancements
- Other
> model: gemma3 roll back

- src/optimum/rbln/transformers/models/llava/modeling_llava.py
- src/optimum/rbln/transformers/models/qwen3/modeling_qwen3.py
- tests/test_llm.py
----
```
```
----
- Enhancements
- Other
> model(qwen&llava): add docstring

- .github/workflows/rbln_optimum_pytest.yaml
- .github/workflows/rbln_scheduled_test.yaml
This PR fixes scheduled pytest, not to fast-fail.
----
```
```
----
- Enhancements
- Other
> other(ci): No Fail fast on scheduled run

- src/optimum/rbln/transformers/models/decoderonly/decoderonly_architecture.py
- src/optimum/rbln/transformers/models/decoderonly/modeling_decoderonly.py
- src/optimum/rbln/transformers/models/opt/modeling_opt.py
- src/optimum/rbln/transformers/models/qwen2_5_vl/qwen2_5_vl_architecture.py
----
```
```
----
- Enhancements
- Other
> refactor(llm): no wrapper_cfg for LLM

- tests/test_llm.py
----
```
```
----
- Enhancements
- Other
> other: fix pytest

- src/optimum/rbln/transformers/models/decoderonly/modeling_decoderonly.py
----
```
```
----
- Enhancements
- Other
> model: handling DecoderOnlyModels's batch_size when can generate is False.

- src/optimum/rbln/diffusers/pipelines/auto_pipeline.py
Update `auto_pipeline.py` to check `convert_rbln_to_hf_model_name(rbln_class_name)`
against `cls._model_mapping_names.values()` instead of `cls._model_mapping_names`.
Ensures correct validation of model architectures like 'StableDiffusionImg2ImgPipeline'
in `from_pretrained()`.
----
```
```
----
- Enhancements
- `dependency`: Update …
> other(fix): fix RBLNAutoPipelineBase model validation

- .github/version.yaml
----
```
```
----
- Enhancements
- Other
> other: update ci compiler

- pyproject.toml
- uv.lock
----
```
```
----
- Enhancements
- Other
> dependency: update diffusers version

- src/optimum/rbln/transformers/models/qwen2_vl/modeling_qwen2_vl.py
when batch_size>1, the `attention_mask` was not properly given.
----
```
```
----
- Enhancements
- Other
> model: fix input of get_rope_index function

- src/optimum/rbln/transformers/models/seq2seq/modeling_seq2seq.py
----
```
```
----
- Enhancements
- Other
> model: fix typo in seq2seq

- .github/renovate.json
When I tested on my forked repo, that config seems to be enough to track the dependency of diffusers and transformers.
----
```
```
----
- Enhancements
- Other
> dependency: renovate bot

- src/optimum/rbln/transformers/models/qwen2_vl/modeling_qwen2_vl.py
----
```
```
----
- Enhancements
- Other
> doc: qwen2vl config

- pyproject.toml
- uv.lock
----
```
```
----
- Enhancements
- Other
> other: update pytest package (torchcodec)

- src/optimum/rbln/transformers/models/whisper/generation_whisper.py
----
```
```
----
- Enhancements
- Other
> model: update Whisper to raise error if beam > 1
